FROM python:3.11-slim

WORKDIR /app

COPY  requirements.txt .

RUN pip install -r requirements.txt

COPY backend/ backend/
COPY db/ db/


RUN apt-get update && apt-get install -y sqlite3 && rm -rf /var/lib/apt/lists/*

# Initialize SQLite DB
RUN sqlite3 qa.db < db/init.sql


EXPOSE 8000
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]
