name: Deploy to Render try workflow dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "test using workflow dispatch"
        required : true
        
  # push:
  #   branches:
  #     - main
  #     - test1

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
